FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app

COPY My-Panel.sln ./

COPY API/*.csproj ./API/
COPY Infrastructure/*.csproj ./Infrastructure/
COPY Core/*.csproj ./Core/

RUN dotnet restore

COPY . ./

WORKDIR API/
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
ENV ASPNETCORE_URLS=http://+:5000
WORKDIR /app

COPY --from=build-env app/API/out .


ENTRYPOINT ["dotnet", "API.dll"]
